language: generic

os: linux

dist: trusty

addons:
- ssh_known_hosts:
  - 176.31.162.57:22
  apt:
    packages:
    - sshpass

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- docker-compose --version
- docker-compose up -d --build
- docker ps

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: main